stages:
  - build
  - test
  - deploy

variables:
  REGISTRY_SERVER: dk8s-registry.wr.usgs.gov
  IMAGE_TAG: $REGISTRY_SERVER/croplands-web:latest

build:
  stage: build
  image: docker:18
  services:
    - name: usgsastro/dind
      alias: docker
  tags:
    - dind
    - dmz
  script:
    - docker login -u $DK8S_REGISTRY_USER -p $DK8S_REGISTRY_PWD $REGISTRY_SERVER
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    changes:
      - Dockerfile
      - requirements.txt
      - croplands-web/**

test:
  image: usgsastro/kube
  stage: test
  tags:
    - dmz
  script:
    - mkdir ~/.kube
    - echo "$DK8S_CONFIG" > ~/.kube/config
    - kubectl config set-context --current --namespace croplands
    - kubectl apply --dry-run=client -f k8s/

deploy:
  image: usgsastro/kube
  stage: deploy
  tags:
    - dmz
  script:
    - mkdir ~/.kube
    - echo "$DK8S_CONFIG" > ~/.kube/config
    - kubectl config set-context --current --namespace croplands
    - kubectl apply -f k8s/
    - kubectl delete po -l app=croplands-web
  only:
    - master
